### PR TITLE
Ivan Andreu terminado

### PR DESCRIPTION
**Pull request by IvanAndreuRascon**

### CODE REVIEW

**Comment by jvcasillas** [comment]
pisha 

image

**Comment by IvanAndreuRascon** [comment]
Oh no, lei esto "Load the data set of your choice and get information about its structure (remember all code needs to be inside a knitr code chunk)."

No lo lei bien jaja ahora lo cambio, sorry

**Comment by IvanAndreuRascon** [comment]
Ups, 

Arreglado hehe

**Comment by jvcasillas** [comment]
Looks good! Clearly there is another factor needed to account for the two distributions in the plot. 

|                Task                | Points |  Earned |
| :--------------------------------- | -----: | ------: |
| Tidy data                          |      2 | 2       |
| Descriptive stats                  |    0.5 | 0.5     |
| Plot data                          |      1 | 1       |
| Fit bivariate regression           |      1 | 1       |
| Publish to GitHub Pages            |      5 | 5       |
| Successfully submit pull request   |    0.5 | 0.5     |
| **Total**                          |     10 | 10      |

**Pull request merged**
