### PR TITLE
PA1_FeliuRibas

### PR DESCRIPTION
**Pull request by mfeliuribas**
I deleted the examples in the assignment. I hope this is not a problem - if not, I can re-do it.

### CODE REVIEW

**Comment by jvcasillas** [comment]
You shouldn't delete anything in the repo (it will delete those files from `main` when I accept your PR). I'll talk about this more in class next week. For now you don't need to redo anything, just download another copy ([click here](https://github.com/ds4ling/programming_assignments/archive/refs/heads/master.zip)), add the files you deleted back into your copy, and push changes. This will automatically update your PR.

**Comment by mfeliuribas** [comment]
Hi Joseph! Sorry for the confusion, but this way I learnt something new today. Thank you so much for your patience! I think I have done it right.

**Comment by jvcasillas** [comment]
No worries. This is how we learn. As far as I can tell it looks great. 👍🏼

**Comment by jvcasillas** [comment]
|                 Task                | Points |
| :---------------------------------- | -----: |
| Create a dropbox folder             |      1 |
| Include a README.md                 |      1 |
| Create a summaries folder           |      1 |
| Include a summary of Wickham (2015) |      2 |
| Successfully submit a pull request  |      5 |
| **Total**                           |     10 |


Good work @mfeliuribas! Surviving indeed! 😎

**Pull request merged**
