### PR TITLE
Assignment 1 - Alejandro Jaume

### PR DESCRIPTION
**Pull request by ajaumelosa**

### CODE REVIEW

**Comment by jvcasillas** [comment]
There is some weird encoding stuff going on with the files you've created. See here: https://github.com/ajaumelosa/programming_assignments/blob/master/misc/jaume_alejandro/summaries/wickham_2015_summary.md

I wonder if this might be related to the warnings we saw when we opened R this morning (I noticed this happened on Meritxell's computer as well. What program did you use to create and save the README.md file?

**Comment by ajaumelosa** [comment]
@jvcasillas I think I know what happened, Patrick just helped me with it. I created the README.md file using TextEdit on my MacBook instead of creating it on GitHub. Could that be the issue?

**Comment by jvcasillas** [comment]
> @jvcasillas I think I know what happened, Patrick just helped me with it. I created the README.md file using TextEdit on my MacBook instead of creating it on GitHub. Could that be the issue?

It could be. Some text editors do weird things. In the coming weeks I will show you an easy way to generate READMEs right from RStudio. For now, doing it directly in github is fine.

**Comment by jvcasillas** [comment]
@ajaumelosa it doesn't look like this was ever fixed. See here: https://github.com/ajaumelosa/programming_assignments/tree/master/misc/jaume_alejandro 

Did you forget to push the changes after we last talked about this?

**Comment by jvcasillas** [comment]
Merging this anyway. We can trouble shoot your Md file later to see what's going on with the encoding.

**Comment by jvcasillas** [comment]
|                 Task                | Points |
| :---------------------------------- | -----: |
| Create a dropbox folder             |      1 |
| Include a README.md                 |      1 |
| Create a summaries folder           |      1 |
| Include a summary of Wickham (2015) |      2 |
| Successfully submit a pull request  |      5 |
| **Total**                           |     10 |

**Pull request merged**
