### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Kgeovanni**
https://kgeovanni.github.io/presentation/

### CODE REVIEW

**Comment by jvcasillas** [comment]
I think your problem has to do with the file structure of your project. You seem to be looking for the presentation at the wrong address. Based on your repo, it looks like it should be: https://kgeovanni.github.io/online_presentation_/presentation/online_presentation.html

Why do you have so many subfolders? Why didn't you name the Rmd file "index.Rmd"?

**Comment by Kgeovanni** [comment]
The pathway!!! Dios mio. You are so right....
Thank you.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by Kgeovanni** [comment]
Hello professor,

I was so eager to fix the path that I missed your additional questions.
I automatically name the Rmd and should have used the regular "index" name.
I included all the folders. I should have deleted the folders that were not
in use.

I added another repository as it was loading only a white screen, but it is
still not loading.

This is where the new pathway to the new repository I just created.
https://kgeovanni.github.io/presentation2/


-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by Kgeovanni** [comment]
I reached out to Kyle for assistance and we were unable to solve it. It
knits right. I am not sure how to get it to present. I am not sure if you
are available, but I definitely want to make sure that you are able to see
my presentation.

Thank you.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by Kgeovanni** [comment]
Here is an update.

I published another presentation just to make sure I was doing it
correctly. It worked.
https://kgeovanni.github.io/template-presentation/template.html#1

However, when I attempted to publish my site it did not work.
https://kgeovanni.github.io/presentation/index.html#1

I attempted the following solutions:
-review my pathway
-added "index.html"
-reviewed my code and it knits

Will continue to work on it.

Thank you.



-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by jvcasillas** [comment]
That’s fine. just leave it for now and i will take a look. Make sure to add me (in settings).



--

Joseph V. Casillas, PhD

Assistant Professor
Department of Spanish and Portuguese
Rutgers University
www.jvcasillas.com<http://www.jvcasillas.com/>
________________________________

**Comment by jvcasillas** [comment]
If you add me I can try and take a look.

**Comment by jvcasillas** [comment]
I am able to knit your presentation after downloading it, so I imagine the issue is related you the path and your specific settings in this repo. Add me as a collaborator when you get a chance.

**Comment by Kgeovanni** [comment]
Hello Joseph,

Thank you for looking at it. I added you as a collaborator in the settings.

I thought it was the additional codes, xaringanExtra I added.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by jvcasillas** [comment]
Did you turn on the website function in the settings of your repo?

**Comment by Kgeovanni** [comment]
Yes. I turned the website on in the settings Github.



settings -> pages[image: Screen Shot 2021-04-09 at 6.16.59 PM.png]

-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by jvcasillas** [comment]
Something about the way you were loading images wasn't working. I don't have time to figure out why right now, but I got the presentation to knit and show up in the browser (https://kgeovanni.github.io/presentation/index.html#1).  I had to simplify the presentation quite a lot to figure it out. You had added a lot of things from xaringanExtra that were neat, but made it difficult to troubleshoot, so I removed them. So here is what you need to do: open the repo on your computer in RStudio (not on github.com), pull in the newest version, go back through it and add any images or whatever you want, but use `knitr::include_graphics` and not ``.

**Comment by Kgeovanni** [comment]
Good evening,
There were a few new codes I learned to add a panel and images. I will make
the adjustments. Thank you for assistance.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Comment by Kgeovanni** [comment]
I am so happy to share my final html presentation.

https://kgeovanni.github.io/presentation/index.html#1

Thank you so so so much.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.

**Pull request merged**
