### PR TITLE
Merge pull request #1 from ds4ling/master

### PR DESCRIPTION
**Pull request by knf43**
update

### CODE REVIEW

**Comment by knf43** [comment]
pull request 2/4

**Comment by jvcasillas** [comment]
@knf43 I think you meant to pull the ds4ling/programming_assignments commits into your forked copy (knf43/programming_assignments).

**Comment by knf43** [comment]
Yes - haha - thank you! I realized something was off and was trying to figure it out

**Comment by jvcasillas** [comment]
@knf43 the structure of your repo is a bit off. Review point 2 of the instructions and reread the tips at the bottom.

**Comment by knf43** [comment]
@jvcasillas  how are things looking now? 

https://github.com/knf43/programming_assignments/tree/master/misc/students/fernandez_kaylee

**Comment by jvcasillas** [comment]
> @jvcasillas how are things looking now?
> 
> https://github.com/knf43/programming_assignments/tree/master/misc/students/fernandez_kaylee

This looks a lot better but not quite there. Specifically, your assignment (what you did in the Rmd file) is fine, but it looks like you have deleted some files from the root directory (which you don't need to touch) and you have an extra pa2 folder there (i.e., not in your dropbox). 

This is what the root directory should look like (this is a screenshot from the master repo): 

Screen Shot 2021-02-07 at 22 08 46

And this is what yours looks like: 

Screen Shot 2021-02-07 at 22 08 34

It seems you have deleted the main `README.Rmd` and `README.md` files and you have added a `pa2` folder. You don't ever need to touch this level of the repo. You will always do your work inside your dropbox (i.e., misc > students > fernandez_kaylee). 
I think the easiest this to do would be to copy your pa2 folder to your desktop, delete and refork the repo, and then upload it again, and resubmit the pull request.

**Pull request closed without merging**
